name: Custom Workflow

on:
  workflow_dispatch:
    inputs:
      user_input:
        description: 'Enter some input'
        required: true
        default: 'Hello World'

  push:
    branches:
      - main # Adjust the branch as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Store user input
      if: github.event_name == 'workflow_dispatch'
      run: echo "${{ github.event.inputs.user_input }}" > user_input.txt

    - name: Use stored input
      if: github.event_name == 'push'
      run: echo "This is a push event"
